#ifndef __H__CONSTANTS__
#define __H__CONSTANTS__

#ifndef PHYSICS_TIME_STEP
#define PHYSICS_TIME_STEP 0.0005f
#define INV_PHYSICS_TIME_STEP (1.f / PHYSICS_TIME_STEP)
#endif

#ifndef LIMIT_COLLISION_PUSH_APART_FACTOR
#define LIMIT_COLLISION_PUSH_APART_FACTOR 1.f
#endif

#ifndef PHYSICS_DAMPING_FACTOR
#define PHYSICS_DAMPING_FACTOR .95f
#endif

#ifndef FLOATING_ERROR_COUNTERING
#define FLOATING_ERROR_COUNTERING .0000001f
#endif

#endif //__H__CONSTANTS__